return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.6",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 55,
  height = 18,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 8,
  nextobjectid = 72,
  properties = {},
  tilesets = {
    {
      name = "background",
      firstgid = 1,
      filename = "background.tsx"
    },
    {
      name = "terrain",
      firstgid = 3,
      filename = "terrain.tsx"
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "bgObj",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 2,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 55,
      height = 18,
      id = 1,
      name = "tile0",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztz8ENABAMRuHuvxGGwBBYA4k7kdA0eV/y33roEwEAAAD+CNoPPJS1H7jgDu+stc0uv5Y2s9YWZd9kta2M1cM1pR9vdR3MIR0="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 55,
      height = 18,
      id = 3,
      name = "tile1",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20KP6AAAACAlwEPeAAB"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 55,
      height = 18,
      id = 4,
      name = "tile2",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20KP6AAAACAlwEPeAAB"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "entities",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 55,
      height = 18,
      id = 6,
      name = "tile4",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20KP6AAAACAlwEPeAAB"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 55,
      height = 18,
      id = 7,
      name = "tile5",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztwTEBAAAAwqD1T20KP6AAAACAlwEPeAAB"
    }
  }
}
