on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this release:
            - Improved performance
            - Bug fixes

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-artifacts
          # path: build-bin

      - name: Upload Windows Zip
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          # path: my_app_windows.zip
